facebookresearch/seamless_communication

docs/m4t/on_device_README.md

1. Fixed spelling of "protocol"
2. Rephrased the sentence to make it clear that the protocol is similar to what Whisper used for evaluation

Fix typos and grammar

---

scripts/m4t/predict/README.md
scripts/m4t/predict/predict.py
src/seamless_communication/models/inference/translator.py

Description:
- dtype set to torch.float16 for GPU inference and torch.float32 for CPU inference, made the output of `WaveformToFbankConverter` consistent with the model's dtype
- implemented a `load_model_for_inference`
- did away with `synthesize_speech` method since it's doesn't do much, users can directly call self.vocoder() for synthesizing speech
Fixes https://github.com/facebookresearch/seamless_communication/issues/47
Test inference:
CPU:
m4t_predict привет t2tt eng --src_lang rus
2023-08-23 12:23:30,130 INFO -- m4t_scripts.predict.predict: Running inference on the CPU.
Using the cached checkpoint of the model 'seamlessM4T_large'. Set `force=True` to download again.
Using the cached tokenizer of the model 'seamlessM4T_large'. Set `force=True` to download again.
Using the cached …

Fix dtype issues with CPU inference, minor refactoring to Translator.

---

.gitignore
scripts/m4t/finetune/dataset.py
src/seamless_communication/datasets/huggingface.py

After https://github.com/facebookresearch/seamless_communication/pull/17 we can restore unit extraction in dataset preparation scripts
Tests:
```
python scripts/m4t/finetune/dataset.py --source_lang eng --target_lang kor --split validation --save_dir ~/dataset
```
Checked units of one sample from the generated dataset. Using vocoder and whisper produced an audio and its transcription: 
Original audio text: `이 역동적인 수송 셔틀은 어떤 식으로든 모든 사람들이 자가용을 기반으로 하는 수송 시스템과 연결되고 이를 지원하도록 한다`
Transcription of the audio, generated from the units: `이 역동적인 수송 셔틀은 어떤 식으로든 모든 사람들이 자가용을 기반으로 하는 수송 시스템과 연결되고 이를 지원하도록 한다.
`

Re-enable unit extraction in dataset preparation script

---

src/seamless_communication/models/inference/translator.py

Adding `max_len_a`and `max_len_b` for text/unit as arguments to `Translator`'s `predict`

Add max_len args in Translator

---

ggml/requirements.txt

Remove transformers dependency to fix https://github.com/facebookresearch/seamless_communication/security/dependabot/1
It's not needed by us, it's there for other projects in ggml I think, and @gwenzek already removed them.

Update ggml requirements.txt

---

ggml/README.md
ggml/examples/common.h
ggml/examples/unity/CMakeLists.txt

- Fix `pkg-config` import of `sndfile`. Tested on macOS and Ubuntu
- Remove `unity_params_parse` and `unity_print_usage ` declarations from `common` for now
```bash
$ ▶ ./bin/unity -m seamlessM4T_medium.ggml
little-endian
open_ggml_file: loading model from 'seamlessM4T_medium.ggml'
load_model_weights: model size:  6542.93 MB, memory used:  6543.31 MB, memory reserved:  6543.31 MB
Enter audio_path and tgt_lang, separated by space (or 'exit' to quit):
jfk.wav eng
Translating (Transcribing) jfk.wav to eng
So, my fellow Americans, don't ask what your country can do for you, ask what you can do for your country.
Enter audio_path and tgt_lang, separated by space (or 'exit' to quit):
```

ggml : update cmake to build on macOS

---

demo/m4tv2/app.py

Summary: the gradio demo currently uses the meta-private repo for the snapshot weights, this fixes it to use the public URL
Test Plan: ran python app.py and it successfully downloads the weights
Reviewers:
Subscribers:
Tasks:
Tags: accept2ship

[demo] m4tv2: fix snapshot path to use public repo

---

demo/m4tv2/app.py

Summary: /home/user/app/models is not a valid path in general. instead, we pull the current logged-in user from getpass.getuser() and interpolate the username into the path.
Test Plan: ran python app.py and was able to boot the demo successfully
Reviewers:
Subscribers:
Tasks:
Tags: accept2ship

[demo] m4tv2: fix checkpoint download path

---

src/seamless_communication/streaming/agents/online_text_decoder.py

There is a bug in the MMA text decoder agent policy that throws an error is some edge cases, particularly when the generated token size reaches/exceed the `max_len`.
This can be reproduced as follows:
```
...
File ".../src/seamless_communication/models/unity/length_regulator.py", line 35, in forward
upsampled_seqs[b, : upsampled_seq_lens[b]] = seqs[b].repeat_interleave(
RuntimeError: repeats must have the same size as input along dim
```
The fix involves moving the while loop stop condition from teh start of the loop to after the decoder pass (but before the token is added to the prediction list).  
Tested that the inference finishes successfully after the fix.

Fix S2S pipeline edge case error

---

ggml/examples/unity/unity.cpp
ggml/include/ggml/ggml.h

use ggml-alloc.h for the encoder too.
I'm setting generous memory buffer, but also this can be tweaked depending on the input lenght and the model dim.
I also had to revert the `GGML_MAX_NODES` changes. I didn't notice before testing on main, but with too big max nodes, I get segfaults. 
I believe those are needed for the large model though, so I'm not sure what's the best way to handle this.

allocr for encoder

---

README.md

#240 from @sanchit-gandhi has updated the various READMEs with mentions of the use of transformers. However, the mention of transformers in the main README is currently under [the gradio demos section](https://github.com/facebookresearch/seamless_communication?tab=readme-ov-file#running-seamlessm4t--seamlessexpressive-gradio-demos-locally), which doesn't really fit.
This PR moves it to a more relevant section and also updates the hyperlinks to remove redundancy with the M4T readme.
cc @elbayadm, @cndn and @sanchit-gandhi

Move Transformers section in readme

---

docs/m4t/README.md
src/seamless_communication/cli/m4t/predict/README.md
src/seamless_communication/cli/m4t/predict/predict.py

- Adding detailed `seamless_communication` inference instruction to the main M4T README for a one-stop shop to get started on using the model.
-  Fixing Transformers instructions for into-text tasks.
- Using `torchaudio` for saving to avoid loading more un-necessary third-party libraries.
- `model.sampling_rate` -> `model.config.sampling_rate`
- Adding resampling (16kHz) to `m4t_predict`.
Testing S2ST:
```
m4t_predict "https://www2.cs.uic.edu/~i101/SoundFiles/preamble10.wav" --task s2st --tgt_lang fra --output_path m4t_pred_output.wav --model_name seamlessM4T_v2_large
2023-12-13 21:20:31,874 INFO -- seamless_communication.cli.m4t.predict.predict: Running inference on device=device(type='cuda', index=0) with dtype=torch.float16.
Using the cached tokenizer of seamlessM4T_v2_large. Set …
```

Inference instructions for M4T

---

docs/m4t/README.md

Fixing `model.sampling_rate` to `model.config.sampling_rate`.

Fix HF model sampling_rate in M4T README.md

---

ggml/examples/unity/model_loader.cpp
ggml/examples/unity/model_loader.h
ggml/ggml_convert.py
ggml/test_unity_cpp.py

Following a user request, I'm adding the `--fp16` flag to `ggml_convert.py` to save the model in half precision.
This helps keep the model on disk size small.
Currently `model_loader.cpp` will automatically upcast `float16` tensors to `float32` , but we could expose a flag to allow keeping the weights in fp16.
I've had to change my first version of the PR because I didn't realized we published `.ggml` artifact, and we would have needed to re-upload them.
I've also added the `--layer_filter` flag to `ggml_convert.py` to remove uneeded layer.
Example usage:
```
python ggml_convert.py -m seamlessM4T_medium --fp16 --layers '^(speech_encoder|text_decoder|final_proj)' -o seamlessM4T_medium_s2t.fp16.ggml
sing the cached checkpoint of seamlessM4T_medium. Set `force` to `True` to download again. …
```

save model as fp16

---

src/seamless_communication/cli/m4t/finetune/README.md
src/seamless_communication/cli/m4t/finetune/dataloader.py
src/seamless_communication/cli/m4t/finetune/finetune.py
src/seamless_communication/cli/m4t/finetune/trainer.py
src/seamless_communication/datasets/huggingface.py

* Update forward pass for for M4T-large-v2
* switch to fairseq2 fbank extractor
* switch to AdamW optimizer (instead of Adam)
* for stability added filters on max audio input length and NaNs in extracted fbanks
* trim unused model parameters to save GPU memory
* Minor code adjustments for MyPy
* Updated README
Tested 3 finetuning regimes, also tested SPEECH_TO_TEXT with M4T-v2-large.

Adjust M4T example finetuning script to align with November changes

---

.gitignore
src/seamless_communication/cli/m4t/evaluate/evaluate.py
src/seamless_communication/cli/m4t/predict/predict.py

The problem I had with `m4t_evaluate` is that the inputs it expects are different from those of `m4t_finetune` and what `m4t_prepare_dataset` generates. Evaluate expects a TSV file and directories while both the others work with a manifest JSON file.
I have changed the `m4t_evaluate` to accept the same inputs as the other two, i.e. a manifest JSON file.
The `--data_file` input can now be either a TSV path or a manifest path.
Also, `--output_path` is now required because the CLI fails otherwise.
<details>
<summary>Here is a sample run with just 3 lines in a manifest JSON file</summary>
<pre>▶ m4t_evaluate --data_file build/fleurs/test_manifest_1.json --task ASR --tgt_lang eng --output_path build/fleurs
Using the cached tokenizer of seamlessM4T_v2_large. Set `force` to `True` to download …

Enable using `m4t_evaluate` with a Manifest JSON file

---

src/seamless_communication/cli/m4t/finetune/dataset.py

I got this error while downloading Fleurs dataset for Spanish.
```
$ m4t_prepare_dataset --source_lang spa --target_lang spa ...
ValueError: No language code mapping for spa(M4T)->??(FLEURs). Please expand `UNITY_TO_FLEURS_LANG_MAPPING`
```
And I've fixed this here. `spa(M4T) -> es_419(FLEURs)`

Added Spanish langcode mapping

---

setup.py
src/seamless_communication/cli/m4t/finetune/dataset.py

It is now possible to download another dataset, other than Google Fleurs. It is necessary to first [sign the Gigaspeech agreement](https://huggingface.co/datasets/speechcolab/gigaspeech) and get access to the dataset, then [create a Huggingface token](https://huggingface.co/docs/hub/en/security-tokens) and to use this while calling the CLI.
```
m4t_prepare_dataset \
--name speechcolab/gigaspeech \
--split xs \
--source_lang eng \
--target_lang eng \
--save_dir gigaspeech/xs \
--huggingface_token <TOKEN>
```

Enable downloading Gigaspeech

---

src/seamless_communication/cli/m4t/evaluate/evaluate.py
src/seamless_communication/cli/m4t/finetune/dataloader.py
src/seamless_communication/cli/m4t/finetune/finetune.py
src/seamless_communication/cli/m4t/finetune/trainer.py
src/seamless_communication/datasets/huggingface.py

This fixes some issues with M4T finetuning CLI and enables freezing parts of a model before training
**Example:**
```
m4t_finetune \
--train_dataset gigaspeech/xs/xs_train_manifest.json \
--eval_dataset gigaspeech/xs/xs_validation_manifest.json \
--batch_size 10 \
--eval_steps 1000 \
--learning_rate 0.00008 \
--patience 10 \
--save_model_to checkpoints/expt5_m4tM.pt \
--model_name seamlessM4T_medium \
--freeze_layers \
model.speech_encoder_frontend \
model.speech_encoder \
model.text_encoder_frontend \
model.text_decoder.layers.0 \
model.text_decoder.layers.1 \
model.text_decoder.layers.2
```

Fixed finetuning trainer and enable freezing layers

---

src/seamless_communication/cli/m4t/finetune/dataset.py

The path was hardcoded, might cause issues.

Fix potential issue with downloading Gigaspeech

---

src/seamless_communication/cli/m4t/finetune/trainer.py

https://github.com/facebookresearch/seamless_communication/pull/449 broke this: it added a parameter and only updated one callsite and not both. I used the same value right now, happy to change

Fix finetuning script

---

src/seamless_communication/cards/nano.yaml
src/seamless_communication/inference/transcriber.py
src/seamless_communication/models/unity/builder.py

Adding extra small versions of unity models for ASR across 5 languages (eng, por, spa, rus, hin).
Example usage: 
```
from seamless_communication.inferenceimport Transcriber
transcriber = Transcriber("seamless_nano")
print(transcriber.transcribe("/home/mavlyutov/input.wav", src_lang="eng"))
transcriber = Transcriber("seamless_micro")
print(transcriber.transcribe("/home/mavlyutov/input.wav", src_lang="eng"))
```
```
Downloading the tokenizer of ...
100%|██| 558k/558k [00:00<00:00, 7.68MB/s]
Downloading the checkpoint of seamless_nano...
100%|██113M/113M [00:03<00:00, 31.5MB/s]
Using cache found in /home/mavlyutov/.cache/torch/hub/snakers4_silero-vad_master
When you call someone who is thousands of miles away, you are using a satellite.
Using the cached tokenizer of . Set `force` to `True` …
```

Adding Seamless Nano transcription models

---

src/seamless_communication/cli/m4t/finetune/README.md

- Fix broken m4t_prepare_dataset guides cause from https://github.com/facebookresearch/seamless_communication/pull/443

Fix broken m4t_prepare_dataset guides
